name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker build & push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: l7r7/sample
          tag-custom: latest
          tag-semver: |
            {{raw}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Debug outputs
        run: echo ${{ steps.docker_meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
