name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker build & push
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - name: Generate tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["l7r7/sample:latest","'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["l7r7/sample:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
